services:
  - type: web
    name: pixabay-telegram-bot
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8496475334:AAFVBYMsb_d_K80YkD06V3ZlcASS2jzV0uQ
      - key: ADMIN_ID
        value: "7251748706"
      - key: PIXABAY_API_KEY
        value: 51444506-bffefcaf12816bd85a20222d1
      - key: PORT
        value: "10000"
      - key: WEBHOOK_URL
        value: https://pixabay-telegram-bot.onrender.com